### PR TITLE
Added an offline version of protocol documentation to the project.

### PR DESCRIPTION
**Pull request by Slushnas**
This feature adds over two megabytes of protocol documentation to the project in a separate folder.  Is that ok or do we need to use a more dynamic option like using wget to download the pages separately from the build?

### CODE REVIEW

**Comment by Mag-nus** [comment]
I like the idea of wget so the tool always has access to the latest docs.

**Comment by Slushnas** [comment]
Yeah I like the idea of having it be dynamic and not expanding the build size but I also see a couple downsides to doing it that way:
1. Is it likely Zegeger will return and update the docs?
2. If we kept the files with the project or hosted it somewhere else we could make any needed changes ourselves and keep things up to date that way.

I still think it would be a good idea to have the docs publicly hosted somewhere where it can be easily edited by others... I would assume the number of people hitting his site and scraping the docs would be small but there is that to think about as well.

Let me know your thoughts on all this.

**Comment by LtRipley36706** [comment]
at one point the idea was to host the files in this repo:
https://github.com/ACEmulator/acemulator.github.io

i would think that should still be workable

**Comment by Slushnas** [comment]
Would we be able to integrate the VS publish check for updates feature with the docs and possibly with AC Log View itself?

**Comment by Slushnas** [comment]
Not ready for merge yet. We still need to work out some details on how to grab the documentation dynamically.

**Pull request merged**
